version: '3.8'

services:
  # Frontend
  frontend:
    build: .
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3001/api

  # Backend
  backend:
    build: ./backend
    ports:
      - "3001:3000"
    depends_on:
      - mongodb
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/promocoes
      - PORT=3000
      - NODE_ENV=production

  # MongoDB
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=promocoes

volumes:
  mongodb_data: